export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const GET_LIVE_STREAM = "GET_LIVE_STREAM"
export const SET_SELECTED_METRIC = "SET_SELECTED_METRIC";
export const HISTORICAL_DATA_SUCCESS = "HISTORICAL_DATA_SUCCESS"
export const HISTORICAL_DATA_ERROR = "HISTORICAL_DATA_ERROR"
export const HISTORICAL_DATA_LOADING ='HISTORICAL_DATA_LOADING'
export const SUBSCRIPTION_DATA_SUCCESS = "SUBSCRIPTION_DATA_SUCCESS"
export const SUBSCRIPTION_DATA_ERROR = "SUBSCRIPTION_DATA_ERROR"
export const SUBSCRIPTION_DATA_LOADING ='SUBSCRIPTION_DATA_LOADING'


 
 
 
 //NOT USED RIGHT NOW
 // export const TUBING_PRESSURE_RECEIVED = "TUBING_PRESSURE_RECEIVED";
// export const FLARE_DATA_RECEIVED = "FLARE_DATA_RECEIVED";
// export const OIL_TEMP_RECEIVED = "OIL_TEMP_RECEIVED";
// export const INJ_VALVE_STATUS = "INJ_VALVE_STATUS";
// export const WATER_TEMP_RECEIVED = "WATER_TEMP_RECEIVED";
// export const CASING_PRESSURE_RECEIVED = "CASING_PRESSURE_RECEIVED";