export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const GET_LIVE_STREAM = "GET_LIVE_STREAM"
export const SET_SELECTED_METRIC = "SET_SELECTED_METRIC";
export const HISTORICAL_DATA_SUCCESS = "HISTORICAL_DATA_SUCCESS"
export const HISTORICAL_DATA_ERROR = "HISTORICAL_DATA_ERROR"
export const HISTORICAL_DATA_LOADING ='HISTORICAL_DATA_LOADING'
export const SUBSCRIPTION_DATA_SUCCESS = "SUBSCRIPTION_DATA_SUCCESS"
export const SUBSCRIPTION_DATA_ERROR = "SUBSCRIPTION_DATA_ERROR"
export const SUBSCRIPTION_DATA_LOADING ='SUBSCRIPTION_DATA_LOADING'


 
 
 