export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const TUBING_PRESSURE_RECEIVED = "TUBING_PRESSURE_RECEIVED"
export const FLARE_DATA_RECEIVED = "FLARE_DATA_RECEIVED"
export const OIL_TEMP_RECEIVED = "OIL_TEMP_RECEIVED"
export const SET_SELECTED_METRIC = "SET_SELECTED_METRIC"